apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: oppositereaction.rocks
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: or-server-clusterip-srv
                port:
                  number: 4000