apiVersion: apps/v1
kind: Deployment
metadata:
  name: or-server-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: or-server
  template:
    metadata:
      labels:
        app: or-server
    spec:
      containers:
        - name: or-server
          image: sofarawaydev/or-server:0001
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: srv-secret
                  key: database-name
                  optional: false
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: srv-secret
                  key: database-url
                  optional: false
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: srv-secret
                  key: public-key
                  optional: false
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: srv-secret
                  key: private-key
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: or-server-clusterip-srv
spec:
  selector:
    app: or-server
  type: ClusterIP
  ports:
    - name: or-server
      protocol: TCP
      port: 80
      targetPort: 3000

