apiVersion: v1
kind: Pod
metadata:
  name: or-server
spec:
  containers:
    - name: or-server
      image: sofarawaydev/or-server:0.0.1
      env:
        - name: PORT
          value: "3000" 
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: srv-secret
              key: database-name
              optional: false                      
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: srv-secret
              key: database-url
              optional: false                    
        - name: PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: srv-secret
              key: public-key
              optional: false
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: srv-secret
              key: private-key
              optional: false